SimpleCTF:
  Game:
    Queue:
      MaxPlayersPerTeam: 4
      MinPlayersPerTeam: 1
      QueueCountdown: 10
    Match:
      MatchTime: 600
  Strings:
    Prefix: "<#eb6434>SimpleCTF » <#e8cd33>"
    Warnings:
      NoPermission: "<red>You don't have the permission to execute that command!"
      NoFriendlyFire: "You can not attack your teammates!"
      WrongBannerTeam: "You cannot break your own flag!"
    Queue:
      TeamJoin: "You joined the %color% team!"
      TeamLeave: "You left the team."
      PlayerJoinedTeam: "%player% joined the team!"
      PlayerLeftTeam: "%player% left the team."
    Match:
      MatchWin: "The %color% team won the match!"
      MatchTimeOut: "The match ran out of time!"
      MatchStart: "The match just started!"
      PlayerCaughtFlag: "%player% CAUGHT THE %color% FLAG!"
      PlayerPlaceFlag: "%player% placed back their flag!"