SimpleCTF:
  Game:
    MaxPlayersPerTeam: 4
    MinPlayersPerTeam: 1
    MatchTime: 600
  Strings:
    Prefix: "<#eb6434>SimpleCTF » <#e8cd33>"
    Match:
      TeamJoin: "You joined the %color% team!"
      TeamLeave: "You left the team."
      PlayerJoinedTeam: "%player% joined the team!"
      PlayerLeftTeam: "%player% left the team."
      MatchWin: "The %color% team won the match!"

