name: SimpleCTF
version: '${version}'
main: me.kugelbltz.simpleCTF.SimpleCTF
api-version: '1.21'
commands:
  capturetheflag:
    description: Capture the flag main command
    aliases:
      - ctf
      - simplectf